### ISSUE TITLE
Overview modern CLI libraries for Python 3

### ISSUE THREAD

**Issue by d1rebear** [d1rebear/git-featured#11]
To choose proper library ('framework') for CLI implementation, we need an overview. List of modern libraries with pros/cons for each is expected as a result of this research.

**Comment by walnut1657** [comment]
- [CEMENT](https://docs.builtoncement.com/)
Its a full fledge CLI framework. Is used in Amazon [Elastic](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3.html), QLDS [Live server administration](https://qlds-manager.readthedocs.io/en/stable/index.html), Pubkey [setup private/public key server connections](https://github.com/fxstein/pubkey)

- [DOCOT](http://docopt.org/)
Lightweight python package for creating command line interface easily by parsing POSIC-style or Markdown usage instructions. It doesn't look flexible.

- [Argparse](https://docs.python.org/3/library/argparse.html)
It's the default python module for creating command lines programs. It provides all the features you need to build a simple CLI. 

- [CLICK](https://github.com/pallets/click)
Click is a Python package for creating beautiful command line interfaces in a composable way with as little code as necessary. It's the "Command Line Interface Creation Kit". It's highly configurable but comes with sensible defaults out of the box.
It aims to make the process of writing command line tools quick and fun while also preventing any frustration caused by the inability to implement an intended CLI API.
